<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<artifactId>uai-parent</artifactId>
		<groupId>com.uni.uai</groupId>
		<version>1.0-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>uai-mcp-base</artifactId>
	<packaging>jar</packaging>

	<name>uai-mcp-base</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<jackson.version>2.13.4</jackson.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.uni.uai</groupId>
			<artifactId>uai-rag</artifactId>
			<version>1.0-SNAPSHOT</version>
		</dependency>
	
		<dependency>
			<groupId>io.modelcontextprotocol.sdk</groupId>
			<artifactId>mcp</artifactId>
			<version>0.10.0</version>
		</dependency>

		<!--与langchain4j相关 ，在server使用llm，用于意图识别-->
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-open-ai</artifactId>
			<version>1.8.0</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j</artifactId>
			<version>1.8.0</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-mcp</artifactId>
			<version>1.8.0-beta15</version>
		</dependency>
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-experimental-sql</artifactId>
			<version>1.8.0-beta15</version>
		</dependency>
		<!--rag-->
		<!--ES-->
		<dependency>
		    <groupId>dev.langchain4j</groupId>
		    <artifactId>langchain4j-elasticsearch</artifactId>
		    <version>1.8.0-beta15</version>
		</dependency>
		<!-- 升级 Elasticsearch Java 客户端到 8.15.x（与服务版本匹配） -->
		<dependency>
			<groupId>co.elastic.clients</groupId>
			<artifactId>elasticsearch-java</artifactId>
			<version>8.15.3</version> <!-- 至少 8.0+，推荐与 Elasticsearch 服务版本一致 -->
		</dependency>
		<!--pdf文档解析器，用于rag-->
		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j-document-parser-apache-pdfbox</artifactId>
			<version>1.8.0-beta15</version>
		</dependency>


		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<version>5.0.0</version>
		</dependency>
		
		        <!-- WebSocket API -->
        <dependency>
            <groupId>jakarta.websocket</groupId>
            <artifactId>jakarta.websocket-api</artifactId>
            <version>2.0.0</version>
            <scope>provided</scope>
        </dependency>

		<!--ubag相关-->
		<dependency>
			<groupId>com.uni.ubag</groupId>
			<artifactId>ubag-data-trad</artifactId>
			<version>2.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <artifactId>neo4j</artifactId>
                    <groupId>org.neo4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>neo4j-java-driver</artifactId>
                    <groupId>org.neo4j.driver</groupId>
                </exclusion>
            </exclusions>
		</dependency>
		
		<dependency>
			<groupId>com.uni.ubag</groupId>
			<artifactId>ubag-util</artifactId>
			<version>2.0-SNAPSHOT</version>
		</dependency>

		<!--支持Prompt中${var}解析-->
		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
			<version>2.3.34</version>
		</dependency>
		<dependency>
			<groupId>cglib</groupId>
			<artifactId>cglib</artifactId>
			<version>2.2.2</version>
		</dependency>

		<!--支持chatMemory中消息的序列化和反序列化为json时的特殊符号处理-->
		<dependency>
			<groupId>com.mikesamuel</groupId>
			<artifactId>json-sanitizer</artifactId>
			<version>1.2.3</version>
		</dependency>

	</dependencies>

	<build>
	</build>


</project>
