#log相关的配置
ubag.log.enable = true
#是否启用数据推动
ubag.log.timer.task.push.enable = true
#日志推送服务的接口地址
ubag.log.timer.task.push.server.url = http://log.ubag.lianjia.com/common/json/api/commonLog_add

#ubag的projectid，每个项目值不同，必须传递
ubag.log.project.id = 270
#日志value的长度
ubag.log.length.value = 100000
#日志result的长度
ubag.log.length.result = 100000

#启动Logger对象（注意，不是ubag的log），打印日志
ubag.log.logger.enable = true
#忽略日志检查的key，例如，有一些公司健康检查的url，没有logId，没有logId，可以忽略logId验证. 或一些项目自身的一些定时任务
ubag.log.id.verify.exclude.key.regex = /actuator






