package com.uni.uai.demo.agent;

import dev.langchain4j.agentic.Agent;
import dev.langchain4j.service.V;

/**
 * 非 AI Agent：以 mock 方式生成 Openclaw Skill 线上商店单页 HTML，写入共享状态 {@code code}。
 */
public class OpenclawStoreHtmlGenerator {

    @Agent(
            value = "Openclaw Skill 商店页面生成（mock，不调用大模型）",
            outputKey = "code"
    )
    public String generateStoreHtml(@V("request") String userRequest) {
        System.out.println("[OpenclawStoreHtmlGenerator] 开始生成 HTML，用户请求标题: " + userRequest);
        String title = userRequest == null || userRequest.isBlank() ? "Openclaw Skill 商店" : userRequest.trim();
        String safe = escapeHtml(title);
        String html = buildOpenclawStorePage(safe);
        System.out.println("[OpenclawStoreHtmlGenerator] 生成完成，长度=" + html.length() + " 字符，已写入 key=code");
        return html;
    }

    private static String escapeHtml(String raw) {
        if (raw == null) {
            return "";
        }
        return raw.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }

    private static String buildOpenclawStorePage(String title) {
        return """
                <!DOCTYPE html>
                <html lang="zh-CN">
                <head>
                  <meta charset="UTF-8"/>
                  <meta name="viewport" content="width=device-width, initial-scale=1"/>
                  <title>%s</title>
                  <style>
                    :root { color-scheme: dark light; --bg: #0f1419; --card: #1a2332; --accent: #3d9cf5; --text: #e7ecf3; }
                    body { font-family: system-ui, sans-serif; margin: 0; background: var(--bg); color: var(--text); }
                    header { padding: 1.25rem 1.5rem; border-bottom: 1px solid #2a3544; display: flex; align-items: center; justify-content: space-between; }
                    h1 { font-size: 1.15rem; margin: 0; }
                    .badge { background: #243044; color: #8ab4ff; padding: 0.2rem 0.55rem; border-radius: 999px; font-size: 0.75rem; }
                    main { max-width: 960px; margin: 0 auto; padding: 1.5rem; }
                    .grid { display: grid; gap: 1rem; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); }
                    article { background: var(--card); border-radius: 10px; padding: 1rem; border: 1px solid #2a3544; }
                    article h2 { font-size: 0.95rem; margin: 0 0 0.35rem; color: var(--accent); }
                    p { margin: 0; font-size: 0.85rem; opacity: 0.9; line-height: 1.45; }
                    .price { margin-top: 0.6rem; font-weight: 600; color: #7ee787; }
                    footer { text-align: center; padding: 2rem; font-size: 0.8rem; opacity: 0.65; }
                  </style>
                </head>
                <body>
                  <header>
                    <h1>%s</h1>
                    <span class="badge">Openclaw Skill Store · Demo</span>
                  </header>
                  <main>
                    <p style="margin-bottom:1rem;font-size:0.9rem;">本页由 AI 自主开发系统 Demo（Non-AI Agent 流水线）mock 生成，用于岗位能力评估展示。</p>
                    <div class="grid">
                      <article><h2>Claw Git</h2><p>仓库与 PR 自动化 Skill。</p><div class="price">免费</div></article>
                      <article><h2>Claw Docs</h2><p>文档索引与站内搜索 Skill。</p><div class="price">¥9/月</div></article>
                      <article><h2>Claw Notify</h2><p>多渠道告警与值班 Skill。</p><div class="price">¥19/月</div></article>
                      <article><h2>Claw Deploy</h2><p>一键预览环境 Skill。</p><div class="price">¥29/月</div></article>
                    </div>
                  </main>
                  <footer>Generated by com.uni.uai.demo.agent · OpenclawStoreHtmlGenerator</footer>
                </body>
                </html>
                """.formatted(title, title);
    }
}
